// The simplest way to check a recursive function

// Sum the numbers until it gets to the base case.

// We will not handle negative numbers in this function
function sum(n: number): number {
  console.log('Number called: ', n)
  // Base case
  if (n === 1) {
    return 1
  }

  // We shall recurse!
  return n + sum(n - 1)
}

console.log(sum(10))

// rA = Return Address - Needs to know who called it to return the value to
// rV = Return Value - The value generated by the function
// A = Arguments - Function arguments
